#! /usr/bin/bash

file_name=$(echo $1 | grep -oP '^[^.]*')

compile(){
 gcc $1 -o $file_name
 if [ $? -eq 0 ];
 then
  printf "\n---Output---\n\n"
  ./$file_name
 else
  printf "\nError during compilation. Exiting!\n"
 fi
}

if [ -f $file_name ];
then
 if [ $1 -ot $file_name ];
 then
  printf "\n---Output---\n\n"
 ./$file_name
 else
  compile $1
 fi
else
 compile $1
fi
exit
